### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by mozharovsky** [Athlee/InteractiveGraphView#5]
## Tasks
- [ ] Add stroke animation for drawing a curve
- [ ] Add gradient animation for drawing a gradient 
- [ ] Add position/fade animation for showing labels
